stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    - npm install
    - npm run build

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    # Ajoute ici tes commandes de déploiement
  only:
    - main  # Déployer uniquement sur la branche main
