stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
     - .npm

build:
  stage: build
  image: node:16  # Utilisation d'une image Node.js
  script:
  - node -v  # Vérifier la version de Node.js
  - npm -v   # Vérifier la version de npm


test:
  stage: test
  image: node:16  # Utilisation d'une image Node.js pour les tests
  script:
    - echo "Running tests..."
    - npm test

deploy:
  stage: deploy
  image: node:16  # Utilisation d'une image Node.js pour le déploiement si nécessaire
  script:
    - echo "Deploying the application..."
    # Ajoute ici tes commandes de déploiement
  environment:
    name: production
    url: https://example.com  # Remplace par l'URL de ton application
  only:
    - main  # Déployer uniquement sur la branche main
