stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:16  # Utilisation d'une image Node.js
  script:
    - echo "Building the project..."
    - npm install
    - npm run build

test:
  stage: test
  image: node:16  # Utilisation d'une image Node.js pour les tests
  script:
    - echo "Running tests..."
    - npm test

deploy:
  stage: deploy
  image: node:16  # ou une autre image si tu as besoin d'outils spécifiques
  script:
    - echo "Deploying the application..."
    # Ajoute ici tes commandes de déploiement
  only:
    - main  # Déployer uniquement sur la branche main
