image: node:14

stages:
  - install
  - build
  - test

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test
